---
- name: Create a EC2 instance
  hosts: localhost
  gather_facts: False
  
  vars:
    region: eu-central-1
    instance_type: t2.micro
    ami: ami-0e342d72b12109f91  
    keypair: my-key3
    
  tasks:
    - name: Create an ec2 instance
      local_action: 
         module: ec2
         key_name: "{{ keypair }}"
         group: launch-wizard-2
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1 
         vpc_subnet_id: subnet-f927cb85
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: hw
      loop: "{{ ec2.instances }}"
    
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"
    
- name: Install nginx
  hosts: hw
  remote_user: ubuntu
  become: true
  gather_facts: no
  tasks:
   - name: Install nginx
     apt:
       name: nginx
       state: present
