---
- name: Create a EC2 instance
  hosts: localhost
  gather_facts: False
  
  vars:
    region: eu-central-1
    instance_type: t2.micro
    ami: ami-0e342d72b12109f91  
    keypair: my-key3
    
  tasks:
    - name: Create an ec2 instance
      local_action: 
         module: ec2
         key_name: "{{ keypair }}"
         group: launch-wizard-2
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true 
         region: "{{ region }}"
         count: 1 
         vpc_subnet_id: subnet-f927cb85
         assign_public_ip: yes
      register: myinstanceinfo

    - debug:
        msg: "ip addres instance  =  {{ myinstanceinfo.instances[0]| json_query('public_ip_address') }}"
  
    - name: Add new instance to hosts and hw group
      add_host:
        hostname: "{{ myinstanceinfo.instances[0]| json_query('public_ip_address') }}"
        groups: hw
    
- name: Install nginx
  hosts: hw
  remote_user: ubuntu
  become: true
  gather_facts: true
  
  tasks:
   - name: Install nginx
     apt:
       name: nginx
       state: present
   
   - name: Upload default index.html for host
     copy: src=~/site/index.html dest=/var/www/html/index.html mode=0644