---
- name: Create a EC2 instance
  hosts: localhost
  gather_facts: False
  
  vars:
    region: eu-central-1
    instance_type: t2.micro
    ami: ami-0e342d72b12109f91  
    keypair: my-key2
    
  tasks:
    - name: Create an ec2 instance
      local_action: 
         module: ec2
         key_name: "{{ keypair }}"
         group: launch-wizard-2
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1 
         vpc_subnet_id: subnet-f927cb85
         assign_public_ip: yes
      register: ec2

    - name: Add the newly created host so that we can further contact it
      add_host:
        name: "{{ item.public_ip }}"
        groups: hw
        with_items: "{{ ec2.instances }}"

    - name: Install app   
      hosts: webservers
      remote_user: ubuntu
      become: yes
      gather_facts: no
        tasks:
         - name: Install Nginx
           apt:
             name: nginx
             state: present
         - service: 
             name: nginx
             state: started
             enabled: yes